version: '2'

services:
 v2ray:
    image: rico93/v2ray_v3_auto:api_alpine
    restart: always
    network_mode: "host"
    environment:
      sspanel_url: "https://xxxx"
      key: "xxxx"
      docker: "true"
      speedtest: "false"
      node_id: 10
    logging:
      options:
        max-size: "10m"
        max-file: "3"